### ISSUE TITLE
After 17/04/24 game update stop working

### ISSUE THREAD

**Issue by derwil86** [xenonchi/loa-radiant#7]
program stopped showing any data after theamine update. I replaced database core-meta for new but dont help.

**Comment by xenonchi** [comment]
I updated to the latest meter-core version now, do the following to update:
1. run git pull to get the latest version
2. in ui/node-modules, delete meter-core
3. in ui, run npm i to reinstall it

**Comment by derwil86** [comment]
Thanks buff atk working now in program dont show brand debuff. Problem is on new guardian and new theamine ride

I have always "No boss detected"
