### ISSUE TITLE
Brand debuff dont show  on new guardian and new theamine ride

### ISSUE THREAD

**Issue by derwil86** [xenonchi/loa-radiant#8]
Thanks buff atk working now in program dont show brand debuff. Problem is on new guardian and new theamine ride

I have always "No boss detected"

_Originally posted by @derwil86 in https://github.com/xenonchi/loa-radiant/issues/7#issuecomment-2067024053_

**Comment by xenonchi** [comment]
Thanks for reporting this issue. I have whitelisted the new bosses, git pull to get the new update. 

Also, I don't have access to the 1630 content, so let me know if those bosses are still not detected.

**Comment by derwil86** [comment]
I dont use git, just download zip. I downloaded and replace modified files but dont help.

I need all step of installation again?

**Install Packages**

In pkt, run npm i to install node modules
In ui, run npm i to install node modules
In ui, run npx electron-rebuild to rebuild modules compiled in a different Node.js version

**Build**

In pkt, run npm run build-dist
Copy pkt/dist/api.js to ui/electron/pkt/api.cjs
In ui, run npm run make to build the executable
In ui/out/LOA-Radiant-win32-x64, run LOA-Radiant.exe

**Comment by derwil86** [comment]
I done new fresh instalation but not help too.

**Comment by xenonchi** [comment]
What is the issue now?

If you download as zip, you will need to re-install packages and re-build. I suggest learning git because it is not very difficult and it makes updating much easier.

**Comment by derwil86** [comment]
I done all, download zip and done all steps. No change still new guardian and new raid not show brand debuff.

**Comment by derwil86** [comment]
Update: brand working on Theamine now, guardian not

**Comment by derwil86** [comment]
electron/pkt/api.cjs is "Vescal", I think need be Veskal


Update: works after change  "Vescal" to "Veskal":). Thx

**Comment by xenonchi** [comment]
Great, thanks for testing
